name: Release dot-face, dot-face-passive-liveness

on:
  repository_dispatch:
    types: dot_face_release
jobs:
  release:
    name: Release dot-face, dot-face-passive-liveness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Release dot-face
        run: |
          cd dot-face
          mkdir $DOT_FACE_VERSION || true
          cp dot-face_template.podspec $DOT_FACE_VERSION/dot-face.podspec || true
          cd $DOT_FACE_VERSION
          sed -i "s/{version}/$DOT_FACE_VERSION/g" dot-face.podspec
        env:
          DOT_FACE_VERSION: "${{github.event.client_payload.dot_face_version}}"
      
      - name: Release dot-face-passive-liveness
        run: |
          cd dot-face-passive-liveness
          mkdir $DOT_FACE_VERSION || true
          cp dot-face-passive-liveness_template.podspec $DOT_FACE_VERSION/dot-face-passive-liveness.podspec || true
          cd $DOT_FACE_VERSION
          sed -i "s/{version}/$DOT_FACE_VERSION/g" dot-face-passive-liveness.podspec
        env:
          DOT_FACE_VERSION: "${{github.event.client_payload.dot_face_version}}"
      
      - name: Update iface dependancy version for dot-face
        if: github.event.client_payload.iface_version != 'null'
        run: |
          cd dot-face
          sed -i "s/    s.ios.dependency 'iface'.*$/    s.ios.dependency 'iface', '$IFACE_VERSION'/g" dot-face_template.podspec
          cd $DOT_FACE_VERSION
          sed -i "s/    s.ios.dependency 'iface'.*$/    s.ios.dependency 'iface', '$IFACE_VERSION'/g" dot-face.podspec
        env:
          DOT_FACE_VERSION: "${{github.event.client_payload.dot_face_version}}"
          IFACE_VERSION: "${{github.event.client_payload.iface_version}}"
      
      - name: Update iface dependancy version for dot-face-passive-liveness
        if: github.event.client_payload.iface_version != 'null'
        run: |
          cd dot-face-passive-liveness
          sed -i "s/    s.ios.dependency 'iface'.*$/    s.ios.dependency 'iface', '$IFACE_VERSION'/g" dot-face-passive-liveness_template.podspec
          cd $DOT_FACE_VERSION
          sed -i "s/    s.ios.dependency 'iface'.*$/    s.ios.dependency 'iface', '$IFACE_VERSION'/g" dot-face-passive-liveness.podspec
        env:
          DOT_FACE_VERSION: "${{github.event.client_payload.dot_face_version}}"
          IFACE_VERSION: "${{github.event.client_payload.iface_version}}"
          
      - name: Release iface
        if: github.event.client_payload.iface_version != 'null'
        run: |
          cd iface
          mkdir $IFACE_VERSION || true
          cp iface_template.podspec $IFACE_VERSION/iface.podspec || true
          cd $IFACE_VERSION
          sed -i "s/{version}/$IFACE_VERSION/g" iface.podspec
        env:
          IFACE_VERSION: "${{github.event.client_payload.iface_version}}"
      
      - name: Push changes
        run: |
          git config --global user.name 'Jakub Vallo'
          git config --global user.email 'jakub.vallo@innovatrics.com'
          git add *
          git commit -m "[dot-face_release workflow] release dot-face, dot-face-passive-liveness $DOT_FACE_VERSION"
          git push
        env:
          DOT_FACE_VERSION: "${{github.event.client_payload.dot_face_version}}"
