name: Release dot-nfc

on:
  repository_dispatch:
    types: dot_nfc_release
jobs:
  release:
    name: Release dot-nfc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Release openssl
        if: github.event.client_payload.openssl_version != ''
        run: |
          cd dot-openssl
          mkdir $OPENSSL_VERSION || true
          cp dot-openssl_template.podspec $OPENSSL_VERSION/dot-openssl.podspec || true
          cd $OPENSSL_VERSION
          sed -i "s/{version}/$OPENSSL_VERSION/g" dot-openssl.podspec
        env:
          OPENSSL_VERSION: "${{github.event.client_payload.openssl_version}}"
          
      - name: Update openssl dependency version for dot-nfc
        if: github.event.client_payload.openssl_version != ''
        run: |
          cd dot-nfc
          sed -i "s/    s.ios.dependency 'dot-openssl'.*$/    s.ios.dependency 'dot-openssl', '$OPENSSL_VERSION'/g" dot-nfc_template.podspec
        env:
          OPENSSL_VERSION: "${{github.event.client_payload.openssl_version}}"

      - name: Release dot-nfc
        run: |
          cd dot-nfc
          mkdir $DOT_NFC_VERSION || true
          cp dot-nfc_template.podspec $DOT_NFC_VERSION/dot-nfc.podspec || true
          cd $DOT_NFC_VERSION
          sed -i "s/{version}/$DOT_NFC_VERSION/g" dot-nfc.podspec
        env:
          DOT_NFC_VERSION: "${{github.event.client_payload.dot_nfc_version}}"
      
      - name: Push changes
        run: |
          git config --global user.name 'Jakub Vallo'
          git config --global user.email 'jakub.vallo@innovatrics.com'
          git add *
          git commit -m "[dot-nfc_release workflow] release dot-nfc $DOT_NFC_VERSION"
          git push
        env:
          DOT_NFC_VERSION: "${{github.event.client_payload.dot_nfc_version}}"
