# This is a basic workflow to help you get started with Actions

name: dot_release

on:
  repository_dispatch:
    types: dot_release
jobs:
  release:
    name: Release DOT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Testing
        run: |
          pwd
          ls
      
      - name: Release dot 5.0.0
        run: |
          cd dot_test
          mkdir 5.0.0
          cp dot_template.podspec 5.0.0/dot.podspec
          cd 5.0.0
          sed -i "s/{version}/5.0.0/g" dot.podspec
          
      - name: Push changes
        run: |
          git config --global user.name 'Jakub Vallo'
          git config --global user.email 'jakub.vallo@innovatrics.com'
          git add *
          git commit -m "[dot_release workflow] release dot 5.0.0"
          git push
