name: nfcreader_release

on:
  repository_dispatch:
    types: nfcreader_release
jobs:
  release:
    name: Release NFCReader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Release nfcreader
        run: |
          cd dot-nfcreader
          mkdir $NFCREADER_VERSION || true
          cp dot-nfcreader_template.podspec $NFCREADER_VERSION/dot-nfcreader.podspec || true
          cd $NFCREADER_VERSION
          sed -i "s/{version}/$NFCREADER_VERSION/g" dot-nfcreader.podspec
        env:
          NFCREADER_VERSION: "${{github.event.client_payload.nfcreader_version}}"
      
      - name: Push changes
        run: |
          git config --global user.name 'Jakub Vallo'
          git config --global user.email 'jakub.vallo@innovatrics.com'
          git add *
          git commit -m "[nfcreader_release workflow] release dot-nfcreader $NFCREADER_VERSION"
          git push
        env:
          NFCREADER_VERSION: "${{github.event.client_payload.nfcreader_version}}"
