name: Release sam-face

on:
  repository_dispatch:
    types: sam_face_release
jobs:
  release:
    name: Release sam-face
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Release sam-face
        if: github.event.client_payload.sam_face_version != 'null'
        run: |
          cd sam-face
          mkdir $SAM_FACE_VERSION || true
          cp sam-face_template.podspec $SAM_FACE_VERSION/sam-face.podspec || true
          cd $SAM_FACE_VERSION
          sed -i "s/{version}/$SAM_FACE_VERSION/g" sam-face.podspec
        env:
          SAM_FACE_VERSION: "${{github.event.client_payload.sam_face_version}}"
      
      - name: Push changes
        run: |
          git config --global user.name 'Jakub Vallo'
          git config --global user.email 'jakub.vallo@innovatrics.com'
          git add *
          git commit -m "[sam-face_release workflow] release sam-face $SAM_FACE_VERSION"
          git push
        env:
          SAM_FACE_VERSION: "${{github.event.client_payload.sam_face_version}}"
